- name: mbedtls-3
  tags:
    - mbedtls-3.0.0
    - mbedtls-3.1.0
    - mbedtls-3.2.0
    - mbedtls-3.2.1
    - mbedtls-3.3.0
    - mbedtls-3.4.0
    - mbedtls-3.5.0
  functions:
    - mbedtls_aes_crypt_ecb
    - mbedtls_aes_crypt_cbc
    - mbedtls_aes_crypt_xts
    - mbedtls_aes_crypt_cfb128
    - mbedtls_aes_crypt_cfb8
    - mbedtls_aes_crypt_ofb
    - mbedtls_aes_crypt_ctr
    - mbedtls_internal_aes_encrypt
    - mbedtls_internal_aes_decrypt
    - mbedtls_aria_crypt_ecb
    - mbedtls_aria_crypt_cbc
    - mbedtls_aria_crypt_cfb128
    - mbedtls_aria_crypt_ctr
    - mbedtls_base64_encode
    - mbedtls_base64_decode
    - mbedtls_camellia_crypt_ecb
    - mbedtls_camellia_crypt_cbc
    - mbedtls_camellia_crypt_cfb128
    - mbedtls_camellia_crypt_ctr
    - mbedtls_ccm_encrypt_and_tag
    - mbedtls_ccm_star_encrypt_and_tag
    - mbedtls_ccm_auth_decrypt
    - mbedtls_ccm_star_auth_decrypt
    - mbedtls_chacha20_crypt
    - mbedtls_chachapoly_encrypt_and_tag
    - mbedtls_chachapoly_auth_decrypt
    - mbedtls_cipher_cmac
    - mbedtls_aes_cmac_prf_128
    - mbedtls_ctr_drbg_seed
    - mbedtls_ctr_drbg_random
    - mbedtls_des_crypt_ecb
    - mbedtls_des_crypt_cbc
    - mbedtls_des3_crypt_ecb
    - mbedtls_des3_crypt_cbc
    - mbedtls_dhm_calc_secret
    - mbedtls_ecdh_compute_shared
    - mbedtls_ecdsa_sign
    - mbedtls_ecdsa_verify
    - mbedtls_ecjpake_derive_secret
    - mbedtls_gcm_crypt_and_tag
    - mbedtls_gcm_auth_decrypt
    - mbedtls_hkdf
    - mbedtls_hmac_drbg_random
    - mbedtls_md5
    - mbedtls_poly1305_mac
    - mbedtls_ripemd160
    - mbedtls_rsa_pkcs1_encrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_encrypt
    - mbedtls_rsa_rsaes_oaep_encrypt
    - mbedtls_rsa_pkcs1_decrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_decrypt
    - mbedtls_rsa_rsaes_oaep_decrypt
    - mbedtls_rsa_pkcs1_sign
    - mbedtls_rsa_rsassa_pkcs1_v15_sign
    - mbedtls_rsa_rsassa_pss_sign_ext
    - mbedtls_rsa_rsassa_pss_sign
    - mbedtls_rsa_pkcs1_verify
    - mbedtls_rsa_rsassa_pkcs1_v15_verify
    - mbedtls_rsa_rsassa_pss_verify
    - mbedtls_rsa_rsassa_pss_verify_ext
    - mbedtls_sha1
    - mbedtls_sha256
    - mbedtls_sha512
  clang-append:
    - -g
  target: no_test

- name: mbedtls-2
  tags:
    - mbedtls-2.18.0
    - mbedtls-2.19.0
    - mbedtls-2.20.0
    - mbedtls-2.21.0
    - mbedtls-2.22.0
    - mbedtls-2.23.0
    - mbedtls-2.24.0
    - mbedtls-2.25.0
    - mbedtls-2.26.0
    - mbedtls-2.27.0
    - mbedtls-2.28.0
  functions:
    - mbedtls_aes_crypt_ecb
    - mbedtls_aes_crypt_cbc
    - mbedtls_aes_crypt_xts
    - mbedtls_aes_crypt_cfb128
    - mbedtls_aes_crypt_cfb8
    - mbedtls_aes_crypt_ofb
    - mbedtls_aes_crypt_ctr
    - mbedtls_internal_aes_encrypt
    - mbedtls_internal_aes_decrypt
    - mbedtls_base64_encode
    - mbedtls_base64_decode
    - mbedtls_camellia_crypt_ecb
    - mbedtls_camellia_crypt_cbc
    - mbedtls_camellia_crypt_cfb128
    - mbedtls_camellia_crypt_ctr
    - mbedtls_ccm_encrypt_and_tag
    - mbedtls_ccm_star_encrypt_and_tag
    - mbedtls_ccm_auth_decrypt
    - mbedtls_ccm_star_auth_decrypt
    - mbedtls_chacha20_crypt
    - mbedtls_chachapoly_encrypt_and_tag
    - mbedtls_chachapoly_auth_decrypt
    - mbedtls_ctr_drbg_seed
    - mbedtls_ctr_drbg_random
    - mbedtls_des_crypt_ecb
    - mbedtls_des_crypt_cbc
    - mbedtls_des3_crypt_ecb
    - mbedtls_des3_crypt_cbc
    - mbedtls_dhm_calc_secret
    - mbedtls_ecdh_compute_shared
    - mbedtls_ecdsa_sign
    - mbedtls_ecdsa_verify
    - mbedtls_gcm_crypt_and_tag
    - mbedtls_gcm_auth_decrypt
    - mbedtls_hkdf
    - mbedtls_hmac_drbg_random
    - mbedtls_md5
    - mbedtls_poly1305_mac
    - mbedtls_ripemd160
    - mbedtls_rsa_pkcs1_encrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_encrypt
    - mbedtls_rsa_rsaes_oaep_encrypt
    - mbedtls_rsa_pkcs1_decrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_decrypt
    - mbedtls_rsa_rsaes_oaep_decrypt
    - mbedtls_rsa_pkcs1_sign
    - mbedtls_rsa_rsassa_pkcs1_v15_sign
    - mbedtls_rsa_rsassa_pss_sign
    - mbedtls_rsa_pkcs1_verify
    - mbedtls_rsa_rsassa_pkcs1_v15_verify
    - mbedtls_rsa_rsassa_pss_verify
    - mbedtls_sha1
    - mbedtls_sha256
    - mbedtls_sha512
  clang-append:
    - -g
  target: no_test
  custom-patterns: TRUE

- name: nettle
  tags:
    - nettle_3.4_release_20171119
    - nettle_3.4.1_release_20181204
    - nettle_3.5_release_20190626
    - nettle_3.5.1_release_20190627
    - nettle_3.6_release_20200429
    - nettle_3.7_release_20210104
    - nettle_3.7.1_release_20210217
    - nettle_3.7.2_release_20210321
    - nettle_3.7.3_release_20210606
    - nettle_3.8_release_20220602
    - nettle_3.8.1_release_20220727
    - nettle_3.9_release_20230514
    - nettle_3.9.1_release_20230601
  functions:
    - nettle_sha512_update
    - nettle_sha256_update
    - nettle_sha224_update
    - nettle_sha224_update
    - nettle_sha512_256_update
    - nettle_sha512_224_update
    - nettle_sha384_update
    - nettle_sha3_224_update
    - nettle_sha3_256_update
    - nettle_sha3_384_update
    - nettle_sha3_512_update
    - nettle_streebog256_update
    - nettle_streebog512_update
    - nettle_sm3_update
    - nettle_md5_update
    - nettle_md4_update
    - nettle_md2_update
    - nettle_ripemd160_update
    - nettle_sha1_update
    - nettle_gosthash94_update
    - nettle_aes_encrypt
    - nettle_aes_decrypt
    - nettle_arcfour_crypt
    - nettle_arctwo_encrypt
    - nettle_arctwo_decrypt
    - nettle_blowfish_encrypt
    - nettle_blowfish_decrypt
    - nettle_blowfish_bcrypt_hash
    - nettle_blowfish_bcrypt_verify
    - nettle_camellia_crypt
    - nettle_cast128_encrypt
    - nettle_cast128_decrypt
    - nettle_chacha_crypt
    - nettle_chacha_crypt32
    - nettle_des_encrypt
    - nettle_des_decrypt
    - nettle_des3_encrypt
    - nettle_des3_decrypt
    - nettle_salsa20_crypt
    - nettle_salsa20r12_crypt
    - nettle_serpent_encrypt
    - nettle_serpent_decrypt
    - nettle_sm4_crypt
    - nettle_twofish_encrypt
    - nettle_twofish_decrypt
    - nettle_cbc_encrypt
    - nettle_cbc_decrypt
    - nettle_ctr_crypt
    - nettle_cfb_encrypt
    - nettle_cfb_decrypt
    - nettle_cfb8_encrypt
    - nettle_cfb8_decrypt
    - nettle_xts_encrypt_message
    - nettle_xts_decrypt_message
    - nettle_eax_encrypt
    - nettle_eax_decrypt
    - nettle_eax_digest
    - nettle_gcm_encrypt
    - nettle_gcm_decrypt
    - nettle_gcm_digest
    - nettle_ccm_encrypt
    - nettle_ccm_decrypt
    - nettle_ccm_digest
    - nettle_chacha_poly1305_encrypt
    - nettle_chacha_poly1305_decrypt
    - nettle_chacha_poly1305_digest
    - nettle_ocb_encrypt
    - nettle_ocb_decrypt
    - nettle_ocb_digest
    - nettle_siv_cmac_aes128_encrypt_message
    - nettle_siv_cmac_aes128_decrypt_message
    - nettle_siv_cmac_aes256_encrypt_message
    - nettle_siv_cmac_aes256_decrypt_message
    - nettle_siv_gcm_encrypt_message
    - nettle_siv_gcm_decrypt_message
    - nettle_hmac_update
    - nettle_hmac_digest
    - nettle_poly1305_aes_update
    - nettle_poly1305_aes_digest
    - nettle_hkdf_extract
    - nettle_hkdf_expand
    - nettle_pbkdf2
    - nettle_pbkdf2_hmac_sha1
    - nettle_pbkdf2_hmac_sha256
    - nettle_pbkdf2_hmac_sha512
    - nettle_pbkdf2_hmac_sha384
    - nettle_balloon
    - nettle_rsa_sha1_sign_tr
    - nettle_rsa_sha256_sign_tr
    - nettle_rsa_sha512_sign_tr
    - nettle_rsa_sha1_verify
    - nettle_rsa_sha256_verify
    - nettle_rsa_sha512_verify
    - nettle_rsa_encrypt
    - nettle_rsa_decrypt
    - nettle_dsa_sign
    - nettle_dsa_verify
    - nettle_ecdsa_sign
    - nettle_ecdsa_verify
    - nettle_ed25519_sha512_sign
    - nettle_ed25519_sha512_verify
    - nettle_yarrow256_random
    - nettle_base64_encode_single
    - nettle_base64_decode_single
    - nettle_memxor
  clang-append:
    - -g
  config-commands:
    - ./.bootstrap
    - ./configure

- name: libsodium
  tags:
    - 1.0.13
    - 1.0.14
    - 1.0.15
    - 1.0.16
    - 1.0.17
    - 1.0.18
    - 1.0.19
  functions:
    - sodium_bin2hex
    - sodium_hex2bin
    - sodium_bin2base64
    - sodium_base642bin
    - sodium_increment
    - sodium_add
    - sodium_sub
    - sodium_compare
    - sodium_is_zero
    - sodium_pad
    - sodium_unpad
    - randombytes_random
    - randombytes_uniform
    - randombytes_buf
    - randombytes_buf_deterministic
    - crypto_secretbox_easy
    - crypto_secretbox_open_easy
    - crypto_secretbox_detached
    - crypto_secretbox_open_detached
    - crypto_secretstream_xchacha20poly1305_init_push
    - crypto_secretstream_xchacha20poly1305_push
    - crypto_secretstream_xchacha20poly1305_init_pull
    - crypto_secretstream_xchacha20poly1305_pull
    - crypto_auth
    - crypto_auth_verify
    - crypto_aead_chacha20poly1305_encrypt
    - crypto_aead_chacha20poly1305_decrypt
    - crypto_aead_chacha20poly1305_encrypt_detached
    - crypto_aead_chacha20poly1305_decrypt_detached
    - crypto_aead_chacha20poly1305_ietf_encrypt
    - crypto_aead_chacha20poly1305_ietf_decrypt
    - crypto_aead_chacha20poly1305_ietf_encrypt_detached
    - crypto_aead_chacha20poly1305_ietf_decrypt_detached
    - crypto_aead_xchacha20poly1305_ietf_encrypt
    - crypto_aead_xchacha20poly1305_ietf_decrypt
    - crypto_aead_xchacha20poly1305_ietf_encrypt_detached
    - crypto_aead_xchacha20poly1305_ietf_decrypt_detached
    - crypto_aead_aegis256_encrypt
    - crypto_aead_aegis256_decrypt
    - crypto_aead_aegis256_encrypt_detached
    - crypto_aead_aegis256_decrypt_detached
    - crypto_aead_aegis128l_encrypt
    - crypto_aead_aegis128l_decrypt
    - crypto_aead_aegis128l_encrypt_detached
    - crypto_aead_aegis128l_decrypt_detached
    - crypto_aead_aes256gcm_encrypt
    - crypto_aead_aes256gcm_decrypt
    - crypto_aead_aes256gcm_encrypt_detached
    - crypto_aead_aes256gcm_decrypt_detached
    - crypto_aead_aes256gcm_encrypt_afternm
    - crypto_aead_aes256gcm_decrypt_afternm
    - crypto_aead_aes256gcm_encrypt_detached_afternm
    - crypto_aead_aes256gcm_decrypt_detached_afternm
    - crypto_box_easy
    - crypto_box_open_easy
    - crypto_box_detached
    - crypto_box_open_detached
    - crypto_box_beforenm
    - crypto_box_easy_afternm
    - crypto_box_open_easy_afternm
    - crypto_box_detached_afternm
    - crypto_box_open_detached_afternm
    - crypto_sign
    - crypto_sign_open
    - crypto_sign_detached
    - crypto_sign_verify_detached
    - crypto_box_seal
    - crypto_box_seal_open
    - crypto_generichash
    - crypto_shorthash
    - crypto_pwhash
    - crypto_pwhash_str
    - crypto_pwhash_str_verify
    - crypto_kdf_hkdf_sha256_expand
    - crypto_kdf_hkdf_sha256_extract
    - crypto_kx_client_session_keys
    - crypto_kx_server_session_keys
  clang-append:
    - -g
  config-commands:
    - ./autogen.sh
    - ./configure
