- name: mbedtls-3
  tags:
    - mbedtls-3.0.0
    - mbedtls-3.1.0
    - mbedtls-3.2.0
    - mbedtls-3.2.1
    - mbedtls-3.3.0
    - mbedtls-3.4.0
  functions:
    - mbedtls_aes_crypt_ecb
    - mbedtls_aes_crypt_cbc
    - mbedtls_aes_crypt_xts
    - mbedtls_aes_crypt_cfb128
    - mbedtls_aes_crypt_cfb8
    - mbedtls_aes_crypt_ofb
    - mbedtls_aes_crypt_ctr
    - mbedtls_internal_aes_encrypt
    - mbedtls_internal_aes_decrypt
    - mbedtls_aria_crypt_ecb
    - mbedtls_aria_crypt_cbc
    - mbedtls_aria_crypt_cfb128
    - mbedtls_aria_crypt_ctr
    - mbedtls_base64_encode
    - mbedtls_base64_decode
    - mbedtls_camellia_crypt_ecb
    - mbedtls_camellia_crypt_cbc
    - mbedtls_camellia_crypt_cfb128
    - mbedtls_camellia_crypt_ctr
    - mbedtls_ccm_encrypt_and_tag
    - mbedtls_ccm_star_encrypt_and_tag
    - mbedtls_ccm_auth_decrypt
    - mbedtls_ccm_star_auth_decrypt
    - mbedtls_chacha20_crypt
    - mbedtls_chachapoly_encrypt_and_tag
    - mbedtls_chachapoly_auth_decrypt
    - mbedtls_cipher_cmac
    - mbedtls_aes_cmac_prf_128
    - mbedtls_ctr_drbg_seed
    - mbedtls_ctr_drbg_random
    - mbedtls_des_crypt_ecb
    - mbedtls_des_crypt_cbc
    - mbedtls_des3_crypt_ecb
    - mbedtls_des3_crypt_cbc
    - mbedtls_dhm_calc_secret
    - mbedtls_ecdh_compute_shared
    - mbedtls_ecdsa_sign
    - mbedtls_ecdsa_verify
    - mbedtls_ecjpake_derive_secret
    - mbedtls_gcm_crypt_and_tag
    - mbedtls_gcm_auth_decrypt
    - mbedtls_hkdf
    - mbedtls_hmac_drbg_random
    - mbedtls_md5
    - mbedtls_poly1305_mac
    - mbedtls_ripemd160
    - mbedtls_rsa_pkcs1_encrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_encrypt
    - mbedtls_rsa_rsaes_oaep_encrypt
    - mbedtls_rsa_pkcs1_decrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_decrypt
    - mbedtls_rsa_rsaes_oaep_decrypt
    - mbedtls_rsa_pkcs1_sign
    - mbedtls_rsa_rsassa_pkcs1_v15_sign
    - mbedtls_rsa_rsassa_pss_sign_ext
    - mbedtls_rsa_rsassa_pss_sign
    - mbedtls_rsa_pkcs1_verify
    - mbedtls_rsa_rsassa_pkcs1_v15_verify
    - mbedtls_rsa_rsassa_pss_verify
    - mbedtls_rsa_rsassa_pss_verify_ext
    - mbedtls_sha1
    - mbedtls_sha256
    - mbedtls_sha512
  clang-append:
    - -g
  target: no_test
- name: mbedtls-2
  tags:
    - mbedtls-2.22.0
    - mbedtls-2.23.0
    - mbedtls-2.24.0
    - mbedtls-2.25.0
    - mbedtls-2.26.0
    - mbedtls-2.27.0
    - mbedtls-2.28.0
  functions:
    - mbedtls_aes_crypt_ecb
    - mbedtls_aes_crypt_cbc
    - mbedtls_aes_crypt_xts
    - mbedtls_aes_crypt_cfb128
    - mbedtls_aes_crypt_cfb8
    - mbedtls_aes_crypt_ofb
    - mbedtls_aes_crypt_ctr
    - mbedtls_internal_aes_encrypt
    - mbedtls_internal_aes_decrypt
    - mbedtls_base64_encode
    - mbedtls_base64_decode
    - mbedtls_camellia_crypt_ecb
    - mbedtls_camellia_crypt_cbc
    - mbedtls_camellia_crypt_cfb128
    - mbedtls_camellia_crypt_ctr
    - mbedtls_ccm_encrypt_and_tag
    - mbedtls_ccm_star_encrypt_and_tag
    - mbedtls_ccm_auth_decrypt
    - mbedtls_ccm_star_auth_decrypt
    - mbedtls_chacha20_crypt
    - mbedtls_chachapoly_encrypt_and_tag
    - mbedtls_chachapoly_auth_decrypt
    - mbedtls_ctr_drbg_seed
    - mbedtls_ctr_drbg_random
    - mbedtls_des_crypt_ecb
    - mbedtls_des_crypt_cbc
    - mbedtls_des3_crypt_ecb
    - mbedtls_des3_crypt_cbc
    - mbedtls_dhm_calc_secret
    - mbedtls_ecdh_compute_shared
    - mbedtls_ecdsa_sign
    - mbedtls_ecdsa_verify
    - mbedtls_gcm_crypt_and_tag
    - mbedtls_gcm_auth_decrypt
    - mbedtls_hkdf
    - mbedtls_hmac_drbg_random
    - mbedtls_md5
    - mbedtls_poly1305_mac
    - mbedtls_ripemd160
    - mbedtls_rsa_pkcs1_encrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_encrypt
    - mbedtls_rsa_rsaes_oaep_encrypt
    - mbedtls_rsa_pkcs1_decrypt
    - mbedtls_rsa_rsaes_pkcs1_v15_decrypt
    - mbedtls_rsa_rsaes_oaep_decrypt
    - mbedtls_rsa_pkcs1_sign
    - mbedtls_rsa_rsassa_pkcs1_v15_sign
    - mbedtls_rsa_rsassa_pss_sign
    - mbedtls_rsa_pkcs1_verify
    - mbedtls_rsa_rsassa_pkcs1_v15_verify
    - mbedtls_rsa_rsassa_pss_verify
    - mbedtls_sha1
    - mbedtls_sha256
    - mbedtls_sha512
  clang-append:
    - -g
  target: no_test
